### ISSUE TITLE
Rspec?

### ISSUE THREAD

**Issue by scarroll32** [KonnorRogers/evil_systems#14]
> Maybe in the future?

Any updates on this?

**Comment by ParamagicDev** [comment]
It's should be possible today, just haven't gotten around to updating the docs. No one has really asked for it either :)

give me a little bit and I'll see what I can do!

**Comment by ParamagicDev** [comment]
Its been a while since I looked at RSpec, but youd want something like this in your setup file:

```rb
require 'capybara'
require 'capybara/cuprite'

require 'evil_systems'

EvilSystems.initial_setup
Capybara.default_driver = Capybara.javascript_driver = :evil_cuprite

RSpec.configure do |c|
  c.include EvilSystems::Helpers
end
```
